In [ ]:
#HLT1
# Write a program that allows you to enter 4 numbers and stores them in a file called “Numbers”

task1 = open("numbers.txt","w") # create the file

task1.close()

In [ ]:
num1 = float(input("Enter your first number")) #user inputs
num2 = float(input("Enter your second number"))
num3 = float(input("Enter your third number"))
num4 = float(input("Enter your fourth number"))

task1 = open("numbers.txt","w")
task1.write(f"{num1} {num2} {num3} {num4}") #write the inputted numbers to the file
task1.close()

In [ ]:
#HLT2
# Write a program to ask a student for their percentage mark and convert this to a grade. The conversion will be done in a function called mark_grade
#function to check whether a number has been entered
def floatchecker(nb): 
    try:
        mynum=float(nb)
        return mynum 
    except:
        return None

In [ ]:
# grade conversion function
# def mark_grade(percnt):
#     from numpy import arange
#     #for percnt in arange(90, 100, 0.1):       
#     #if 90 <= percnt < 100:
#     #if percnt in range (90,100):
#         #grade = "A"
#    # for percnt in arange(80, 90, 0.1):
#         grade = "A"
#    # elif percnt in range (80,89):
#         #grade = "B"    
#     elif 80 <= percnt < 90:
#         grade = "B"     
#     return grade

In [ ]:
def mark_grade(percnt):
    grades = [("A", 80), ("B", 65), ("C", 50), ("D", 40), ("E", 30), ("U", 0)]#series of tuple within a list to check. Tupple contains 2 elemnets/index's grade + lower limit
    for mrk in grades: #going/loop through the list
        # (element at index 1) in the tuple), print the resulting grade (index o)
        if percnt >= mrk[1]: #[1] checking index value 1 of each tuple. If equal or greater than the reference value in the tupple
            print(f"Your percentage of {percnt:.1f}%, converts to grade {mrk[0]}")
            break

In [ ]:
print("Grade Conversion Tool")

while True: #loop for valid input
    stugrade = input("Enter your percentage mark") #ask student for percentage
    mynum1 = floatchecker(stugrade)#local variable assigned to the result of the floatchecker function

    if mynum1 != None and mynum1 in range (0,101):
        mymark=mark_grade(mynum1)
        #temp_stugrade= mark_grade(mynum1) #assigning a variable to the output of the mark_grade function to be called upon later
        #print(f"Your converted grade is {temp_stugrade}")
        break
    else:
        print("incorrect input. try again.")

In [166]:
#Numpy HLT1
#Create a 1D array of numbers from 0 to 9
import numpy as np

array=np.array([0,1,2,3,4,5,6,7,8,9])
print(array)

array1=np.arange(10) #evenly spaced array
print(array1)


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [165]:
#Numpy HLT2
#Create a 3×3 NumPy array of all Boolean value Trues
true3x3 = np.full((3,3), True, dtype=bool)
print(true3x3,'\n')

true3x3_1= np.ones((3, 3), dtype=bool)
print(true3x3_1)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]] 

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [164]:
#Numpy HLT3
#Extract all odd numbers from array of 1-10
t3array = np.arange(1, 10) 
print(t3array[t3array%2==1])


[1 3 5 7 9]


In [ ]:
#arr=np.array(range(1,10)) 
#print("even number ",arr[arr%2==0]) 
#print("odd number ", arr[arr%2!=0]) 

In [163]:
#Numpy HLT4
#Replace all odd numbers in an array of 1-10 with the value -1
t4array = np.arange(1, 10)  

t4array[t4array%2==1] = -1   #after dividing by 2 if there is a remainder they will now equal -1          
print (t4array) 

[-1  2 -1  4 -1  6 -1  8 -1]


In [162]:
#Numpy HLT5
#Convert a 1D array to a 2D array with 2 rows
array1Dto2D = np.arange(0,6).reshape(2,3)
print(array1Dto2D)

[[0 1 2]
 [3 4 5]]


In [161]:
#Numpy HLT6
#Create two arrays a and b, stack these two arrays vertically use the np.dot and np.sum to calculate totals
a=np.arange(1,11)
b=np.arange(1,11)
print(a,b)

stackedab = np.vstack((a,b))
print(stackedab)

arraysum= np.sum(stackedab)
print(arraysum)

arraydot = np.dot(a,b)
print(arraydot)


[ 1  2  3  4  5  6  7  8  9 10] [ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]
110
385


In [111]:
#Numpy HLT6.1
# Create the following pattern without hardcoding. Use only NumPy functions. array([1,1,1,2,2,2,3,3,3,1,2,3,1,2,3,1,2,3])
np.concatenate((np.ones(3),np.ones(3)*2,np.ones(3)*3,np.arange(1,4),np.arange(1,4),np.arange(1,4)))

array([1., 1., 1., 2., 2., 2., 3., 3., 3., 1., 2., 3., 1., 2., 3., 1., 2.,
       3.])

In [123]:
#Numpy HLT6.2
# In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) – remove all repeating items present in array b
a = np.arange(1,6)
b = np.arange(4,10)
b2 = np.setdiff1d(b,a)#removes all repeating items from the b array leaving the remainder
print(b2) 

[6 7 8 9]


In [160]:
#Numpy HLT6.3
#Get all items between 3 and 7 from a and b and sum themtogether
conc_ab= np.concatenate((a,b))
print(conc_ab)
#conc_ab=[(conc_ab[conc_ab>=3] and (conc_ab[conc_ab<=7])]
#conc_ab= conc_ab[(conc_ab>=3) and (conc_ab<=7)]
#conc_ab=np.where(conc_ab > 3,conc_ab<=7)
conc_ab = conc_ab[conc_ab>=3]
conc_ab = conc_ab[conc_ab<=7] #new array values for conc_ab now passed through with new condition
print(conc_ab)

sum=np.sum(conc_ab)
print(sum)


[1 2 3 4 5 4 5 6 7 8 9]
[3 4 5 4 5 6 7]
34
